backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "resources/public/images/uploads"
public_folder: "/images/uploads"
# REFERENCE DOCUMENTATION
# https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    sortable_fields: ['date-published', 'title']
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Publish Date", name: "date-published", widget: "datetime", format: "DD-MM-YYYYThh:mm:ssZ"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Is this a draft?", name: "draft", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "og-image", widget: "image", required: false}
      - {label: "UUID", name: "uuid", widget: "string", required: false}

