name: Deploy Site

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    # - uses: DeLaGuardo/setup-clojure@2.0
    #   with:
    #     tools-deps: '1.9.0'
    #
    - run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
        chmod +x linux-install-1.10.1.536.sh
        sudo ./linux-install-1.10.1.536.sh
    - run: clojure deploy.clj
